# Script

from Succes.succes import *

names = []
ids = []


# Logs

Moeru = Succes(489470853072027685)
names.append('Moeru')
ids.append(Moeru)
Moeru.add_succes("Premier personnage")
Moeru.add_succes("Premiers pas")
NsX_Dan_Tan = Succes(328211140213735424)
names.append('NsX_Dan_Tan')
ids.append(NsX_Dan_Tan)
NsX_Dan_Tan.add_succes("Premiers pas")
NsX_Dan_Tan.add_succes("Premier personnage")
Leyas = Succes(424641007007694849)
names.append('Leyas')
ids.append(Leyas)
Leyas.add_succes("Premier personnage")
Leyas.add_succes("Premiers pas")
Ex0Dust_ = Succes(277863039179554826)
names.append('Ex0Dust_')
ids.append(Ex0Dust_)
Ex0Dust_.add_succes("Premier personnage")
Ex0Dust_.add_succes("Premiers pas")
Xanark_ = Succes(577456997666914314)
names.append('Xanark_')
ids.append(Xanark_)
Xanark_.add_succes("Premier personnage")
Xanark_.add_succes("Premiers pas")
sarche = Succes(740298157770145814)
names.append('sarche')
ids.append(sarche)
sarche.add_succes("Premier personnage")
sarche.add_succes("Premiers pas")
Valkyrie_Sensei = Succes(443496030143643650)
names.append('Valkyrie_Sensei')
ids.append(Valkyrie_Sensei)
Valkyrie_Sensei.add_succes("Premier personnage")
Valkyrie_Sensei.add_succes("Premiers pas")
ʏᴜɪ = Succes(709350501522604053)
names.append('ʏᴜɪ')
ids.append(ʏᴜɪ)
ʏᴜɪ.add_succes("Premier personnage")
ʏᴜɪ.add_succes("Premiers pas")
Mr_LePlouc = Succes(436892864451051532)
names.append('Mr_LePlouc')
ids.append(Mr_LePlouc)
Mr_LePlouc.add_succes("Premier personnage")
Mr_LePlouc.add_succes("Premiers pas")
Moeru.add_succes("Maitre de guilde")
NsX_Dan_Tan.add_succes("Compagnon")
Moeru.add_succes("Lanceur d'hostilites")
Moeru.add_succes("Hors la loi")
Moeru.add_succes("Acteur du destin")
Moeru.add_succes("Compagnon")
Moeru.add_succes("Fantome")
Moeru.add_succes("Chasseur de boss (novice)")
Kondaax_fdm = Succes(854066957489012796)
names.append('Kondaax_fdm')
ids.append(Kondaax_fdm)
Kondaax_fdm.add_succes("Premier personnage")
D_Be = Succes(409753153245020162)
names.append('D_Be')
ids.append(D_Be)
D_Be.add_succes("Premier personnage")
NatsuFirewalk = Succes(673451151437594634)
names.append('NatsuFirewalk')
ids.append(NatsuFirewalk)
NatsuFirewalk.add_succes("Premier personnage")
NatsuFirewalk.add_succes("Premiers pas")
NatsuFirewalk.add_succes("Compagnon")
NatsuFirewalk.add_succes("Fantome")
Mr_LePlouc.add_succes("Maitre de guilde")
sarche.add_succes("Proprietaire")
sarche.add_succes("Compagnon")